// Generated by CoffeeScript 1.7.1
define("binnng/random", function(require, exports, module) {
  var random;
  random = function(min, max) {
    return min + Math.random() * (max - min);
  };
  return module.exports = random;
});
